services:
  web:
    image: kubedevio/simulador-do-caos:v1
    ports:
      - 8080:3000
    restart: always
    healthcheck:
      disable: true
    cpuset: "0"
    memswap_limit: 512M
    deploy:
      resources:
        limits: "0.5"
        memory: "512M"